# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b65451abf8e3cd2404f30e64f8e7d95f0b8044d5a27977cbdbbc804b2302ed4a736b5df8dee2bf5bdf12a8c4c6e24f4179fb0a3dcd6f45c452393c79c65097df

test:
  secret_key_base: 66b4224d28b741c1fe0fd41e1452673b82e313881abce1794f70633a6b2c8da2c58bd77fa6635e0b6b82df29b3b2cd64c1dce01235f07b8314ca37558ed32d25

# Do not keep production secrets in the repository,
# instead read values from the environment.
  # secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
production:
  secret_key_base: 714999aa48789ad9f08bc6dccbbbd3401e0bb629b7ab45e5d2937e1aabc56f33e449c3c6802cb77c40aa5776db09b00e868c4187add5e44d34db80a23aaac9f4
